build.version: @project.version@

server:
  port: 8080

logging:
  file.name: '${user.home}/logs/currency-accounts/currency-accounts.log'
  pattern.console: '%d{HH:mm:ss.SSS} %-5level %X{tuuid} %logger{100} : %msg%n'
  level:
    ROOT: INFO
    pl.bsf.lukasz.koc.currencyaccounts: TRACE


spring:
  application.name: currency-accounts

  datasource:
    url: jdbc:h2:mem:currency-accounts-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: dev
    password: ved

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2/console/${user.home}/currency-accounts

nbp:
  exchange:
    rates:
      url: http://api.nbp.pl/api/exchangerates/rates/A/
